=== Rxkasu/golfhandicap/src/json/schema/json-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "user_id": {
      "type": "integer",
      "minimum": 1
    },
    "surname": {
      "type": "string",
      "minLength": 1,
      "maxLength": 40
    },
    "first_name": {
      "type": "string",
      "minLength": 1,
      "maxLength": 40
    },
    "games": {
      "type": "array",
      "items": {
        "oneOf": [ {
          "type": "object",
          "properties": {
            "game_id": {
              "type": "integer",
              "minimum": 1
            },
            "course_name": {
              "type": "string",
              "minLength": 1,
              "maxLength": 60
            },
            "date": {
              "type": "string",
              "minLength": 10,
              "maxLength": 10,
              "pattern": "^(19|20)\\d{2}\/(0[1-9]|1[0,1,2])\/(0[1-9]|[12][0-9]|3[01])$"
            },
            "hcp_index": {
              "type": "number",
              "minimum": -54,
              "maximum": 54
            },
            "course_rating": {
              "type": "number",
              "minimum": 30,
              "maximum": 90
            },
            "slope_rating": {
              "type": "integer",
              "minimum": 55,
              "maximum": 155
            },
            "holes": {
              "type": "array",
              "minItems": 9,
              "maxItems": 9,
              "items": {
                "type": "object",
                "properties": {
                  "hole_id": {
                    "type": "integer",
                    "minimum": 1,
                    "maximum": 18
                  },
                  "par": {
                    "type": "integer",
                    "minimum": 2,
                    "maximum": 6
                  },
                  "hcp": {
                    "type": "integer",
                    "minimum": 1,
                    "maximum": 18
                  },
                  "hits": {
                    "type": "integer",
                    "minimum": 1
                  }
                },
                "required": [
                  "hole_id",
                  "par",
                  "hcp",
                  "hits"
                ]
              }
            }
          },
          "required": [
            "game_id",
            "course_name",
            "date",
            "hcp_index",
            "course_rating",
            "slope_rating",
            "holes"
          ]
        },
        {
          "type": "object",
          "properties": {
            "game_id": {
              "type": "integer",
              "minimum": 1
            },
            "course_name": {
              "type": "string",
              "minLength": 1,
              "maxLength": 60
            },
            "date": {
              "type": "string",
              "minLength": 10,
              "maxLength": 10,
              "pattern": "^(19|20)\\d{2}\/(0[1-9]|1[0,1,2])\/(0[1-9]|[12][0-9]|3[01])$"
            },
            "hcp_index": {
              "type": "number",
              "minimum": -54,
              "maximum": 54
            },
            "course_rating": {
              "type": "number",
              "minimum": 30,
              "maximum": 90
            },
            "slope_rating": {
              "type": "integer",
              "minimum": 55,
              "maximum": 155
            },
            "holes": {
              "type": "array",
              "minItems": 18,
              "maxItems": 18,
              "items": {
                "type": "object",
                "properties": {
                  "hole_id": {
                    "type": "integer",
                    "minimum": 1,
                    "maximum": 18
                  },
                  "par": {
                    "type": "integer",
                    "minimum": 2,
                    "maximum": 6
                  },
                  "hcp": {
                    "type": "integer",
                    "minimum": 1,
                    "maximum": 18
                  },
                  "hits": {
                    "type": "integer",
                    "minimum": 1
                  }
                },
                "required": [
                  "hole_id",
                  "par",
                  "hcp",
                  "hits"
                ]
              }
            }
          },
          "required": [
            "game_id",
            "course_name",
            "date",
            "hcp_index",
            "course_rating",
            "slope_rating",
            "holes"
          ]
        }
      ]
      }
    }
  },
  "required": [
    "user_id",
    "surname",
    "first_name",
    "games"
  ]
}

=== Rxkasu/golfhandicap/tests/data/test-data.json
{
    "user_id": 1,
    "surname": "Maximus",
    "first_name": "Plebertus",
    "games": [
        {
            "game_id": 1,
            "course_name": "Pleb Golf Club 18-hole",
            "date": "2015/04/01",
            "hcp_index": -54,
            "course_rating": 70.9,
            "slope_rating": 115,
            "holes": [
                {
                    "hole_id": 1,
                    "par": 3,
                    "hcp": 4,
                    "hits": 5
                },
                {
                    "hole_id": 2,
                    "par": 4,
                    "hcp": 16,
                    "hits": 6
                },
                {
                    "hole_id": 3,
                    "par": 4,
                    "hcp": 1,
                    "hits": 8
                },
                {
                    "hole_id": 4,
                    "par": 5,
                    "hcp": 10,
                    "hits": 7
                },
                {
                    "hole_id": 5,
                    "par": 4,
                    "hcp": 7,
                    "hits": 6
                },
                {
                    "hole_id": 6,
                    "par": 4,
                    "hcp": 13,
                    "hits": 6
                },
                {
                    "hole_id": 7,
                    "par": 3,
                    "hcp": 5,
                    "hits": 6
                },
                {
                    "hole_id": 8,
                    "par": 4,
                    "hcp": 17,
                    "hits": 6
                },
                {
                    "hole_id": 9,
                    "par": 4,
                    "hcp": 2,
                    "hits": 6
                },
                {
                    "hole_id": 10,
                    "par": 5,
                    "hcp": 11,
                    "hits": 7
                },
                {
                    "hole_id": 11,
                    "par": 4,
                    "hcp": 8,
                    "hits": 6
                },
                {
                    "hole_id": 12,
                    "par": 4,
                    "hcp": 14,
                    "hits": 6
                },
                {
                    "hole_id": 13,
                    "par": 3,
                    "hcp": 6,
                    "hits": 5
                },
                {
                    "hole_id": 14,
                    "par": 4,
                    "hcp": 18,
                    "hits": 6
                },
                {
                    "hole_id": 15,
                    "par": 4,
                    "hcp": 3,
                    "hits": 6
                },
                {
                    "hole_id": 16,
                    "par": 5,
                    "hcp": 12,
                    "hits": 6
                },
                {
                    "hole_id": 17,
                    "par": 4,
                    "hcp": 9,
                    "hits": 5
                },
                {
                    "hole_id": 18,
                    "par": 4,
                    "hcp": 15,
                    "hits": 6
                }
            ]
        },
        {
            "game_id": 2,
            "course_name": "Pleb Golf Club 18-hole",
            "date": "2019/04/02",
            "hcp_index": -37,
            "course_rating": 70.9,
            "slope_rating": 115,
            "holes": [
                {
                    "hole_id": 1,
                    "par": 3,
                    "hcp": 4,
                    "hits": 4
                },
                {
                    "hole_id": 2,
                    "par": 4,
                    "hcp": 16,
                    "hits": 5
                },
                {
                    "hole_id": 3,
                    "par": 4,
                    "hcp": 1,
                    "hits": 5
                },
                {
                    "hole_id": 4,
                    "par": 5,
                    "hcp": 10,
                    "hits": 6
                },
                {
                    "hole_id": 5,
                    "par": 4,
                    "hcp": 7,
                    "hits": 6
                },
                {
                    "hole_id": 6,
                    "par": 4,
                    "hcp": 13,
                    "hits": 5
                },
                {
                    "hole_id": 7,
                    "par": 3,
                    "hcp": 5,
                    "hits": 6
                },
                {
                    "hole_id": 8,
                    "par": 4,
                    "hcp": 17,
                    "hits": 9
                },
                {
                    "hole_id": 9,
                    "par": 4,
                    "hcp": 2,
                    "hits": 5
                },
                {
                    "hole_id": 10,
                    "par": 5,
                    "hcp": 11,
                    "hits": 5
                },
                {
                    "hole_id": 11,
                    "par": 4,
                    "hcp": 8,
                    "hits": 6
                },
                {
                    "hole_id": 12,
                    "par": 4,
                    "hcp": 14,
                    "hits": 6
                },
                {
                    "hole_id": 13,
                    "par": 3,
                    "hcp": 6,
                    "hits": 5
                },
                {
                    "hole_id": 14,
                    "par": 4,
                    "hcp": 18,
                    "hits": 6
                },
                {
                    "hole_id": 15,
                    "par": 4,
                    "hcp": 3,
                    "hits": 6
                },
                {
                    "hole_id": 16,
                    "par": 5,
                    "hcp": 12,
                    "hits": 6
                },
                {
                    "hole_id": 17,
                    "par": 4,
                    "hcp": 9,
                    "hits": 5
                },
                {
                    "hole_id": 18,
                    "par": 4,
                    "hcp": 15,
                    "hits": 6
                }
            ]
        },
        {
            "game_id": 3,
            "course_name": "Humbertus Alley Golf Club 18-hole",
            "date": "2019/04/03",
            "hcp_index": -32.5,
            "course_rating": 72.3,
            "slope_rating": 130,
            "holes": [
                {
                    "hole_id": 1,
                    "par": 3,
                    "hcp": 16,
                    "hits": 4
                },
                {
                    "hole_id": 2,
                    "par": 4,
                    "hcp": 1,
                    "hits": 5
                },
                {
                    "hole_id": 3,
                    "par": 4,
                    "hcp": 10,
                    "hits": 5
                },
                {
                    "hole_id": 4,
                    "par": 5,
                    "hcp": 7,
                    "hits": 6
                },
                {
                    "hole_id": 5,
                    "par": 4,
                    "hcp": 13,
                    "hits": 6
                },
                {
                    "hole_id": 6,
                    "par": 4,
                    "hcp": 4,
                    "hits": 7
                },
                {
                    "hole_id": 7,
                    "par": 3,
                    "hcp": 17,
                    "hits": 4
                },
                {
                    "hole_id": 8,
                    "par": 4,
                    "hcp": 2,
                    "hits": 8
                },
                {
                    "hole_id": 9,
                    "par": 4,
                    "hcp": 11,
                    "hits": 4
                },
                {
                    "hole_id": 10,
                    "par": 5,
                    "hcp": 8,
                    "hits": 5
                },
                {
                    "hole_id": 11,
                    "par": 4,
                    "hcp": 14,
                    "hits": 6
                },
                {
                    "hole_id": 12,
                    "par": 4,
                    "hcp": 5,
                    "hits": 6
                },
                {
                    "hole_id": 13,
                    "par": 3,
                    "hcp": 18,
                    "hits": 5
                },
                {
                    "hole_id": 14,
                    "par": 4,
                    "hcp": 3,
                    "hits": 6
                },
                {
                    "hole_id": 15,
                    "par": 4,
                    "hcp": 12,
                    "hits": 6
                },
                {
                    "hole_id": 16,
                    "par": 5,
                    "hcp": 9,
                    "hits": 6
                },
                {
                    "hole_id": 17,
                    "par": 4,
                    "hcp": 15,
                    "hits": 5
                },
                {
                    "hole_id": 18,
                    "par": 4,
                    "hcp": 6,
                    "hits": 6
                }
            ]
        },
        {
            "game_id": 4,
            "course_name": "Humbertus Alley Golf Club 18-hole",
            "date": "2019/04/04",
            "hcp_index": -27.5,
            "course_rating": 72.3,
            "slope_rating": 130,
            "holes": [
                {
                    "hole_id": 1,
                    "par": 3,
